### ISSUE TITLE
CommonJS support via esm

### ISSUE THREAD

**Issue by FallingSnow** [HydreIO/rgraph#15]
I wish I could use ESM on everything but support for it just isn't where it needs to be. Things like my ava tests just don't want to work with it. My fork https://github.com/fallingsnow/rgraph adds commonjs support using esm.

Would you be interested in a pull request?

**Comment by Sceat** [comment]
I pretty much against that too, that would be supporting the past and adding complexity to the library by downgrading the tech :/, i run my whole company code on esm so if you need help to switch feel free to contact me

**Comment by FallingSnow** [comment]
Thanks for the support. I finally got it using https://github.com/avajs/ava/pull/2540. Gonna go ahead and delete my fork now.
